MYSQL_ALPHACASH_ADMIN_USER = 'root'
MYSQL_ALPHACASH_ADMIN_PWD = 'root'
MYSQL_ALPHACASH_HOST = '10.102.66.238'
MYSQL_ALPHACASH_PORT = 2306
MYSQL_ALPHACASH_DB = 'test'
# 如果为0，直接建立普通短连接；如果大于0，则建立长连接的连接池
pool_size = 0
